bootandy/dust

src/main.rs

This is a really great little tool! I noticed some compiler warnings when I built it locally, and I thought the box construction characters could be slightly fancier, so there you go. I split the changes into several commits, and the only one that changes behavior is the last one, 1c80cbf, "Make printing slightly prettier." I'm not sure this PR is worth merging, just FYI. Also, I might change it a little more aggressively, like factor it into a lib crate and a bin crate, and possibly try to speed it up.

Minor cleanup, prettier output

---

README.md
src/display.rs
src/main.rs
src/tests.rs
src/utils/mod.rs

Following a user request the option '-d N' allows a user to output N
levels of sub directories.
Fixed bug: so that trailing slashes are now removed.

Add support for -d depth flag

---

Cargo.lock
Cargo.toml
README.md
src/display.rs
src/main.rs
src/utils/mod.rs
src/utils/platform.rs

Use a parallel walkdir implementation that is able to fetch more resources at the same time. This should greatly improve directory trees with lots of branching, at the cost of threading. Also make sure to allocate enough space as much as possible ahead of time to avoid reallocation. Lastly, `remove` on a vec needs to make an allocation each time, so prefer the retain method for repeated removal.
Some benchmark on my computer (galago pro 3):
Folder 1 (medium, shallow):
dust: 0.055011367s
du -sh: 0.245766881s
Folder 2 (small, shallow):
du -sh: 0.007830246s
dust: 0.025789946s
Folder 3 (large, deep):
dust: 3.421158887s
du -sh: 21.322613990s

Use jwalk instead of walkdir: parallel walking for performance boost

---

Cargo.toml
src/main.rs
src/utils/mod.rs

Fix: https://github.com/bootandy/dust/issues/44
Resolve issue with the root node not appearing and the root node being repeated on small directories.

Ab bug fix

---

Cargo.lock
Cargo.toml
src/main.rs
src/tests.rs
src/utils/platform.rs

New assert_cli library requires we cast the param passed to 'is()' as
it can no longer cast implicitly. I am guessing this is because it is
due to confusion between whether to cast to u8 or str

Upgrade libraries. Fix assert_cli

---

src/main.rs
src/utils/mod.rs
src/utils/platform.rs

https://github.com/bootandy/dust/issues/50
Add optional -x flag to limit search to the current filesystem.
Add (untested) support for windows for the equivalent of inode and
device.

Support excluding filesystems with -x

---

Cargo.lock
Cargo.toml
src/main.rs

Hacky fix for https://github.com/bootandy/dust/issues/52

Fix dust for single core machines

---

src/main.rs
src/tests.rs
src/utils/mod.rs

https://github.com/bootandy/dust/issues/46
Add -X flag used to ignore any file or directory that matches the
provided substring.
This means that -X e will ignore any file or directory with an 'e' in
it.

Add option to ignore directories

---

Cargo.lock
Cargo.toml
src/utils/platform.rs

The MetadataExt functions are nightly-only right now so we need to call
the windows api ourselves to get the device number.  The winapi_util
package has a nice wrapper to do this for us.
The get_device function doesn't appear to be used anywhere so I removed
it.

Fix get_metadata on windows

---

.github/workflows/CICD.yml
src/display.rs
src/tests.rs
src/utils/mod.rs
src/utils/platform.rs

- adds GitHub-Actions CI workflow (includes arm-linux, x86-linux, macos, and windows builds/testing)
- automatic deployment to Github Releases when commit is version tagged (see example at <https://github.com/rivy/rs.dust/releases/tag/v0.4.9>; note: fully automatically generated)
- improves path manipulation portability
- builds / tests successfully locally and on all CI hosts
- wip / needs further investigation
- feasability of (currently disabled) symlink tests on "windows"
- investigate and/or update tests to handle minor size variations in testing output for different "windows" hosts
- some one byte differences between local and CI host file sizes; ? bug or expected host variation
- `cargo tarpaulin` inability to handle test coverage (use alternate framework?)

Fix windows compilation and testing

---

src/display.rs
src/main.rs
src/utils/mod.rs
src/utils/platform.rs

This minimizes the string conversion/copy "fiddliness" and helps somewhat in code comprehension and maintaining/encouraging cross-platform compatibility. 
There may be some additional work to be done with references, especially in the containers, that might be useful to further minimize copying. But it's a bit beyond my understanding of the language at the moment to go beyond this point.
Let me know if this is helpful, and if so, whether you'd like any changes.

Refactor ~ use Path/PathBuf instead of &str/String

---

src/display.rs
src/main.rs

enable_ansi_support must be run for windows 10 but is not required and
indeed fails if run on windows < 10.
Disable the expect so the code might run on windows 8
may fix:
https://github.com/bootandy/dust/issues/70

Maybe fix windows 8 support

---

src/utils/mod.rs
src/utils/platform.rs

It can be very expensive to do that, especially when it causes windows defender to read the files and scan them.
Savings in orders of magnitude in terms of time, io and cpu have been observed on hdd, windows 10, some 100Ks files taking up some hundreds of GBs:
Consistently opening the file: 30 minutes.
With this optimization:         8 sec.
Hard links: Unresolved. We don't get inode/file index, so hard links count once for each link. Hopefully they are not too commonly in use on windows.

Avoid opening all files for reading on windows

---

.github/workflows/CICD.yml

This fixes the failing empty features issue more generically and robustly.
I just noticed the GHA builds were failing on another repo and created this fix. I see that you've fixed it here by removing support for the features option completely. This implementation works whether the build uses features or not. It'll be more robust in the case that you add any features option at a later date.
Since, you're current implementation works, I understand if you don't want to merge this ... but I think that this is a better version which a future you might appreciate. 😄

Maint/CI ~ fix features option for GHA `cargo ...` and `cross ...`

---

src/display.rs

The enum variant `ansi_term::Colour::Red` (which uses the ANSI color code `31`)
is used instead of the code `196` to display the size of the largest file. This
means that the red color of the terminal theme is used which is probably
preferred by most users.

Change red ANSI color code for size of biggest file

---

src/main.rs
src/utils/mod.rs

Change the depth flag so that it only changes the depth of displayed
subdirectories, not the depth of the directory size calculation (i.e.,
changing --depth does not change the displayed directory size, rather it
only changes how many levels of subdirectories are shown).
Resolves #112

Change behavior of depth flag

---

Cargo.lock
Cargo.toml
src/display.rs

I tried to use [stfu8](https://crates.io/crates/stfu8) package to encode utf-8 characters.  
Maybe this could resolve issue #118.
p.s. I'm not very familiar with Rust, feel free to abandon this.

encode non-printable characters

---

Cargo.toml

It makes life of packager harder.
cargo test works with ansi_term 0.12.1

Be less prescriptive for the ansi_term dep

---

src/display.rs

The old code was subtly different in the way the root node worked. This
changed in the v0.6.0 version when dependencies were removed. The code
to handle file count was never updated
https://github.com/bootandy/dust/issues/162

bugfix: Fix crash when using '-f' flag

---

.github/workflows/CICD.yml

The rules for github actions appear to have changed
Possible fix

Fix ci: Github actions: Publish step

---

tests/test_exact_output.rs

An issue raised that the test output looked a lot like the mac output.
This change causes test to pass if output is either mac or linux style
https://github.com/bootandy/dust/issues/138

Possible test fix: Some tests fail on some linux

---

.github/workflows/CICD.yml
Cargo.toml

Hi! I recently made [an apt repo for Rust cli tools](https://apt.cli.rs/) and I'm interested in adding your tool to the apt repo, because I quite like dust :) I generally would like to download the deb packages directly from your releases, so I don't have to build them myself and everyone can use them as well.
Below is an experimental workflow change that should build debian packages which should statically link against musl so there are no glibc version incompatibilities.

Build Debian packages in CI

---

Cargo.lock
Cargo.toml
README.md
src/dir_walker.rs
src/display.rs
src/filter.rs
src/main.rs
src/node.rs
src/utils.rs
tests/test_flags.rs

replaces: https://github.com/bootandy/dust/pull/174
t = Show summary of types
-e = Filter by regex
allows you to specify a file type like -e ".txt$"
-v = Filter by inverse regex
allows you to ignore a file type like -v ".txt$"
Change behaviour of '-f' flag - it now counts only files. Before it
counted files & directories. This was needed for compatibility with
the new '-e' filter flag

Ignore dir to regex

---

tests/test_flags.rs

For some unknown reason mac takes offence to searching for
'test_dir_unicode'. 'test_dir_hidden' seems to work fine.
This isn't a proper fix as I've just hacked round the problem. Ideally
I'd need a mac user to do some investigation.

Tests: Fix test on mac (hack)

---

.github/workflows/CICD.yml

I get why you don't like working on this. :)
This will build tarballs for Linux aarch64 gnu and musl targets. I couldn't get the musl debs building because I wasn't sure how to provide the correct strip binary. Either way this still seems an improvement towards #200 
Here's the error if you know a quick fix. 
```
/home/runner/.cargo/bin/cargo deb --no-build --target=aarch64-unknown-linux-musl
strip: Unable to recognise the format of the input file `/home/runner/work/dust/dust/target/aarch64-unknown-linux-musl/release/dust'
cargo-deb: unable to strip binary '/home/runner/work/dust/dust/target/aarch64-unknown-linux-musl/release/dust': strip: exit status: 1.
hint: Target-specific strip commands are configured in [target.aarch64-unknown-linux-musl] strip = { path = "strip" } in .cargo/config …
```

add aarch64 gnu and musl cross targets

---

src/dir_walker.rs
src/filter.rs
src/main.rs
src/node.rs

Allow -n for number_of_lines to be used with -d 'max depth'
Remove depth specific functions, the job is now handled by the mainline
Add depth as a field onto the Node object.
https://github.com/bootandy/dust/issues/220

Fix: Allow -n to be used with -d

---

Cargo.toml

This PR would add settings for `cargo`s release profile, optimizing code during build for speed and stripping it for symbols for size

perf: use lto, strip and codegen profile settings for perf opt

---

src/dir_walker.rs

Sort the Node objects so that duplicate inodes appear in a predictable
order.
Include new sort_by_inode method because this is notably quicker than
sorting by size & name as defined in the nodes.rs file.
Should fix: https://github.com/bootandy/dust/issues/234

Fix: Predictable iteration order

---

src/display.rs
src/main.rs
tests/test_flags.rs

Flag to not include the last line containing totals of the output tree
resolves: https://github.com/bootandy/dust/issues/216

Feature: Add skip-total flag

---

src/dir_walker.rs
tests/test_flags.rs

Stop incorrect reporting of "Did not have permissions" this would
happen where dust is called with a file instead of a directory.
https://github.com/bootandy/dust/issues/241

Fix: Permissions

---

src/dir_walker.rs
src/display.rs
src/display_node.rs
src/filter.rs
src/main.rs
src/node.rs
src/platform.rs
src/utils.rs
tests/test_exact_output.rs
tests/test_flags.rs
tests/tests_symlinks.rs

- Try to use iterator adapters and collect in various places, where possible. This especially benefits `draw_it`.
- Try to use `.map` and other similar methods on `Option`s and `Result`s, where possible
- Replaced nearly all `clone`s with reference-based equivalents
- Summarizing nodes by file extension is now much more efficient (significantly fewer allocations)
- `PartialOrd` and `PartialEq` implementations on `Node` and `DisplayNode` now agree with each other (it's no longer possible to construct a `Node` for which `node1 != node2 && !(node1 < node2) && !(node1 > node2)`).
- Replace `#[cfg(...)]` function definitions with simpler if `cfg!(...)` equivalents
- The optimized code is the same and this reduces maintenance burden of keeping signatures synchronized
- Simplify CLI `Values` …

Lots of code cleanup

---

Cargo.lock
Cargo.toml
build.rs
completions/_dust
completions/_dust.ps1
completions/dust.bash
completions/dust.elv
completions/dust.fish
src/cli.rs
src/display.rs
src/main.rs

Support for completions

---

build.rs
src/cli.rs
src/main.rs

Dislike the idea of passing a string into build_cli. By removing a call to default_value we can side-step the problem.

Cleanup previous PR

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs

Sometimes it's nice to run `dust` on a list of files/directories generated programmatically with something like `fd` or read from a file. This PR allows users to do just that:
```shell
$ fd ... | dust
$ dust < list_of_directories.txt
```

Allow reading `inputs` from stdin

---

README.md

[deb-get](https://github.com/wimpysworld/deb-get) allows Ubuntu- and Debian-derived distro users to track and maintain `.deb` packages published authoritatively in 3rd-party apt repos, web sites, `ppa`s and Github releases.
That project is running a [mini-event](https://github.com/wimpysworld/deb-get/issues/579) to spread the word to users of supported projects and to encourage new contributors to reach out to supported projects.
This is submitted in the hope that it might be useful to you and your users.  As I haven't begun to learn rust it is likely to be the only contribution I can offer, but it comes with my thanks for your work on `dust`.  
Thanks.

docs: added deb-get as installation source

---

completions/_dust
completions/_dust.ps1
completions/dust.bash
completions/dust.elv
completions/dust.fish
src/cli.rs
src/dir_walker.rs
src/main.rs

-L is de-reference links similar to du -L
I don't see the need to support -l (ignore symlinks)

Links2 add support for -L 

---

config/config.toml
src/config.rs
src/display.rs
src/main.rs
tests/test_flags.rs

- If `--depth` flag is not defined (or it has an invalid value), a value from the config file will be used.
- If no `depth` entry in the config file (or there is no config file), the default `usize::MAX` will be used.
Added test cases:
- no config and no flag defined              -> `usize::MAX` should be used
- config defined, but flag is not defined    -> config value should be used
- config is not defined, but flag is defined -> flag value should be used
- both config and flag is defined            -> flag value should be used
Additional changes:
- Fixed some clippy issues.
- Added comments to the example `config.toml` file. (copy from flag description)
Closes #314

feat: default option for depth from config file

---

Cargo.toml

Hello! This PR enables [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) to find release builds for the project on github. It uses a [heuristic for finding release packages](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md), which assumes the crate name and release package name are the same. This adds metadata to Cargo.toml to provide the correct name for the github releases and binary name.
I have tested this locally with
```bash
cargo binstall --manifest-path Cargo.toml --disable-strategies quick-install du-dust
```
which results in it correctly finding https://github.com/bootandy/dust/releases/download/v0.8.5/dust-v0.8.5-x86_64-unknown-linux-gnu.tar.gz

Add cargo-binstall metadata to Cargo.toml

---

completions/_dust
completions/dust.bash

Fixes issue: Completions for zsh and bash do not work for the base filename pattern `*`.

Fix filename completions for zsh and bash

---

Cargo.lock
Cargo.toml
src/platform.rs

Resolves #366 
Before: 
After:

feat(win): use size on disk for apparent size for OneDrive files

---

README.md

- Adds the method for installing `dust` from `conda-forge` ([feedstock here](https://github.com/conda-forge/dust-feedstock))
If you'd like to be listed as a package maintainer, please let me know, and I'll add you. Effort is minimal; maintenance is mostly automated.

Add Anaconda install method

---

completions/_dust

- Use `_files` to complete file paths
- Add `_dust_output_formats` for -o/--output-format
- Add missing headings
Fixes https://github.com/bootandy/dust/issues/359

Fix zsh completion

---

src/cli.rs

Currently options following regular arguments are not interpreted as options. This fixes that.
Users can still treat values starting with a hyphen (`-`) as regular arguments by using `--`, e.g.:
dust -d 2 -r ~/Documents -F -- --this-is-my-dir

Allow options to be set in any position

---

src/config.rs
src/display.rs

```
kB - means kilobyte 10**3
KiB - means kibibyte 1024 / 2**10
```

fix: bug: Si detection was backwards.

---

src/display.rs

in src/display.rs file: the following explicit lifetimes could be elided: 'a

Explicit lifecycle that can be omitted

---

src/config.rs

#Background
--only-file displays full paths even without --full-paths #386
If only-file is provided without the --full-pathss parameter, the output file path does not contain the full path
- fix: --only-file displays full paths even without --full-paths
Fix https://github.com/bootandy/dust/issues/386 --only-file displays full paths even without --full-paths

fix: issue 386 --only-file displays full paths even without --full-paths

---

README.md
src/display_node.rs
src/main.rs
src/node.rs

Stop -j writing to a file, print to stdout instead.

refactor: cleanup -j / --output-json flag

---

completions/_dust
completions/_dust.ps1
completions/dust.bash
completions/dust.elv
completions/dust.fish
man-page/dust.1
src/cli.rs
src/config.rs
src/dir_walker.rs
src/main.rs
src/progress.rs
tests/test_exact_output.rs

This PR change the `Did not have permissions..` message to print problematic folders/files
Why this PR: I think it's useful to have the list of the problematic folders/files

eprint problematic folders

---

src/dir_walker.rs
src/main.rs
src/platform.rs
src/utils.rs
tests/test_exact_output.rs

This PR addresses an issue where `target_dirs` were being optimized out before being passed to the `get_filesystem_devices()` function. The changes in this PR ensure that `target_dirs` are passed directly to `get_filesystem_devices()`, and only then are they simplified.
Example of a command that currently doesn't work correctly:
```sh
dust -x $(findmnt -S tmpfs -o target -n)
```
It should show the usage of all tmpfs mounts, but it currently shows just the the root mountpoints like `/run`, since all the mountpoints nested under it are optimized out.

Fix -x option behavior

---

Cargo.lock

starting with 0.1.7, winapi-util uses windows-rs, which is maintained official bindings from MS. this reduces dependence on winapi, which is abandoned for more than 3 years

deps: update winapi-util to 0.1.8

---

src/dir_walker.rs
src/main.rs
src/node.rs
src/platform.rs
src/utils.rs

Previously, the function get_metadata in platform.rs used `fs::metadata` which follows symbolic links and returns metadata for the target file. This caused issues https://github.com/bootandy/dust/issues/421: **du / dust disagreement**  when trying to determine properties of the symbolic link itself   
- fix: retrieve metadata for symbolic links without following them
du / dust disagreement： https://github.com/bootandy/dust/issues/421
cargo test command output
du -s output vs cargo run -- -ok /home/shirley/code/python/official/superset/superset-frontend
du -s -L output vs cargo run -- -ok -L /home/shirley/code/python/official/superset/superset-frontend
while use dust v1.0.0 command,
The output shows that dust v1.0.0 produces the same results regardless of whether the -L parameter is used. …

fix: retrieve metadata for symbolic links without following them

---

completions/_dust
completions/_dust.ps1
completions/dust.bash
completions/dust.elv
completions/dust.fish
man-page/dust.1
src/cli.rs
src/config.rs
src/dir_walker.rs
src/display.rs
src/filter.rs
src/filter_type.rs
src/main.rs
src/node.rs

Dust tree by age https://github.com/bootandy/dust/issues/385
Add a new feature to dust to show the tree by age          
- feat: support Dust tree by age
fix:   Dust tree by age https://github.com/bootandy/dust/issues/385
dust help command output
cargo test run test results
show by accesstime
show by modifiedtime
show by createdtime

feat: support Dust tree by age

---

Cargo.toml
src/progress.rs

`AtomicU64` cannot be used on platforms without 64-bit atomics, such as armel. This PR adds a dependency on the `portable-atomic` crate for those platforms, using the type of the same name defined in it. It introduces no changes for all other platforms (in particular, those on which dust currently builds are unchanged). I tested that this patch cross-builds to armel, and that all tests pass in an emulated armel environment.

fix: 64-bit atomics for platforms with no 64-bit atomics

---

.pre-commit-config.yaml

Use pre-commit hooks to do more checks and optimize submission information before submission.
```
pip3 install pre-commit
pre-commit install
````

feat: use pre-commit hooks to standardize commit messages

---

config/config.toml

Update `iso=true` in the config.toml to `output-format="si"` to fix issue: https://github.com/bootandy/dust/issues/430

Docs: update sample config.toml

---

Cargo.toml

solve issue: https://github.com/bootandy/dust/issues/432
fix: man-page and completions missing in debian package

fix: man-page and completions missing in debian package

---

src/main.rs

The https://github.com/eminence/terminal-size/pull/41 PR mentioned in comments of `get_(height|width)_of_terminal()` (added by https://github.com/bootandy/dust/commit/c36ca33fe973657002905bbdb77c639ac3c006f0)
https://github.com/bootandy/dust/blob/b63608604a768386506b6736f56092583e8fa5a0/src/main.rs#L83-L91
has been merged and shipped since `terminal-size` [v0.2.2](https://github.com/eminence/terminal-size/releases/tag/v0.2.2). As we're using `terminal-size` v0.2.6 now, it's time to simplify them.
https://github.com/bootandy/dust/blob/38c4d237321dcdb4f71f1918ec1cb473ed66655b/Cargo.lock#L766-L768
Not sure if I made it to the most simplified form, as I can hardly speak Rust.
cc @Lucretiel

refactor: simplify `get_height_of_terminal()` and `get_width...`

---

src/display.rs

As in #448, volumes greater than 1000TB do not pretty format. This has been addressed, and additional tests have been added for large folders.

Enable pretty format for petabyte data

---

.github/workflows/CICD.yml
src/config.rs
src/dir_walker.rs
src/utils.rs

Hello
This PR
- fix the typo `Operator`
- Fixed with `typos -w` https://github.com/crate-ci/typos
- add typos to the CI/CD using typos actions - https://github.com/marketplace/actions/typos-action

fix typo Operator

---

src/dir_walker.rs
src/progress.rs

Rust may throw Interrupted errors while scanning filesystem. These may be retried:
https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.Interrupted
Fixes:
https://github.com/bootandy/dust/issues/420

fix: Handle Interrupted Error

---

src/display.rs

Before we calculated the % by taking the longest bar. If you use --skip-total the longest bar is not the total. Remove this special case as it was wrong.

fix: Bars in --skip-total flag

---

src/display.rs
src/filter.rs
src/main.rs
tests/test_flags.rs

If we run `dust /usr/*/Trash`
We see several 'Trash' directories in the output but do not know which user they belong to.
This fix means if we see duplicate names in a directory we will display the parent directory name as well
for: https://github.com/bootandy/dust/issues/441

feat: Handle duplicate dir names better

---

src/dir_walker.rs
src/main.rs
src/utils.rs

Allow excluding any directory or file by absolute path using the `-X` option.
The proposed change for the `ignore_file` function checks whether the file's absolute path representation starts with any of the absolute path representations of ignored directories. Any file inside an ignored folder should have a common path with the ignored directory.
Fixes: #471

fix: Support absolute path with `-X` option

---

src/dir_walker.rs
src/main.rs
src/progress.rs

Previously, we attempted to perform a clean shutdown, which could take a significant period of time on slow filesystems. This commit changes the shutdown logic to unconditionally abort immediately when ^C is received by the program.
This PR resolves #477.

feat: Abort immedietly when ^C is received.

---

src/config.rs
src/progress.rs
tests/test_flags.rs

Progress spinner and status line are written to stderr instead of stdout.
No longer any need to detect if stdout is being redirected.

fix: status mesages go to stderr not stdout

---

src/platform.rs

The [std::fs::Metadata](https://doc.rust-lang.org/beta/std/fs/struct.Metadata.html) struct sometimes contains incorrect information on how many blocks are allocated to a certain file on an NTFS mount. When that happens, the struct could have an unfathomably large block count that is unrelated to the file's real size.
The proposed fix determines how much space could be allocated to a certain file using `md.blksize()`. As far as I know, a file should only have up to one extra operating system block or page allocated for it, typically an extra 4 KB at most. The fixed code uses the same calculation as before by default (`reported_size = md.blocks() * get_block_size()`), but uses the `max_size` when it is smaller than the `reported_size`. The `max_size` should be smaller than the …

Fix miscalculation of NTFS mount file sizes inside WSL

---

src/platform.rs

Clean up get_metadata by removing unused return

style: Cleanup method

---

src/dir_walker.rs

This may be causing dust to lock up as we were accidentally creating a second editable_error causing threads to lock.
https://github.com/bootandy/dust/issues/495

fix: bug: Remove bad error handling

---

src/filter.rs

Today I met a small bug introduced at 74ffd7890194bf850b75dc4ff0fd72ce358c8a00 . When I run `dust -d0 -c -B path1 path2 ...`, the previous released version prints something like:
```plaintext
12K   ┌── test_dir │                                                 ██████████████████████████ │  33%
24K   ├── test_dir2│                        ███████████████████████████████████████████████████ │  67%
36K ┌─┴ (total)    │███████████████████████████████████████████████████████████████████████████ │ 100%
```
Current latest version turns to display something like (only total, no other lines):
```plaintext
36K ┌── (total)│███████████████████████████████████████████████████████████████████████████████ │ 100%
```
The bug comes from 74ffd7890194bf850b75dc4ff0fd72ce358c8a00 , which seems to accidently …

Fix multi-paths output when `depth` is `0`
