- src/tests.rs
Macos does not appear to have a predictable iteration order of the files
> Fix tests on mac

- src/display.rs
- src/main.rs
- src/tests.rs
- src/utils/mod.rs
Also handle case where an argument is a substring of another argument
> wip: code to remove duplicate arguments

- Cargo.toml
- src/display.rs
A small change to update to the newest edition of Rust.
> Upgrade to the 2018 edition

- Cargo.lock
- Cargo.toml
- src/main.rs
clap does most of this for you - I had forgotten to wire it up
https://github.com/bootandy/dust/issues/33
increment build version
> Provide version information with -V

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/tests.rs
Newest versions remove a lot of sub-dependencies
> Latest deps

- Cargo.lock
- Cargo.toml
- src/display.rs
- src/main.rs
- src/tests.rs
https://github.com/bootandy/dust/issues/37
> Add flag for No color, refactor tests

- src/utils/mod.rs
- src/utils/platform.rs
This code now won't compile on none-(windows/unix family)
systems. [unix family includes mac]
Removing this method allows us to remove an Option and simplify the code
slightly
> Simplify inodes & devices by removing Option

- Cargo.lock
- Cargo.toml
- src/display.rs
- src/main.rs
- src/utils/mod.rs
Based of https://github.com/bootandy/dust/pull/104
Idea is to allow users to find the number of files in each directory
instead of size.
> Support listing directories by number of files

- tests/test_flags.rs
Covers the case fixed by the previous commit
> Add test to check behaviour of -d flag

- Cargo.lock
- src/main.rs
Small fix for multi arguments.
Update packages
> Ab small fix

- src/display.rs
- src/main.rs
- src/utils/mod.rs
> Print correct message when paths are not found

- src/display.rs
- src/main.rs
Implement ISO output as suggested in #182.
> Feature: Implement ISO output

- src/platform.rs
Fixes https://github.com/bootandy/dust/issues/153
> Fix archive/directory check in platform.rs

- src/utils.rs
Refactor simplify_dir_names to make it more readable
> Refactor: tweak utils function

- tests/tests_symlinks.rs
> Predictable order: Update tests

- Cargo.lock
- Cargo.toml
- config/config.toml
- src/config.rs
- src/main.rs
Read flags for several params from config file.
This was a popular requested feature (many people want to run with -r on
by default).
> Feature: Config file

- .github/workflows/CICD.yml
- README.md
Resolved via `prettier --write .`
> Prettify md/yaml file

- Cargo.lock
- Cargo.toml
- build.rs
- man-page/dust.1
This writes the man page to the source code repository and I have checked in the resulting file.
I'm not very certain that the way you want to have this done, but I tried to follow the pattern of how the command completion files are generated.
Please come with feedback or nitpicks and I can rework the PR :)
closes #45
> generate a man page as part of the build

- src/main.rs
Wrap and ignore these panics.
I can't reproduce this problem but I'm curious to know if this fixes it
> Fix: some panics are occuring when creating rayon

- src/dir_walker.rs
- src/main.rs
- src/progress.rs
- tests/test_flags.rs
Provide "No such file or directory" error if file is not found. Provide "Unknown Error" if other error found
Should reduce confusion from the generic other error
> feat: better error messages

- Cargo.lock
- Cargo.toml
- src/dir_walker.rs
- src/main.rs
- src/progress.rs
before ctrl-c would not cancel a running job.
https://github.com/bootandy/dust/issues/367
> feat: Listen for ctrl-c

- completions/_dust
- completions/_dust.ps1
- completions/dust.bash
- completions/dust.elv
- completions/dust.fish
- man-page/dust.1
- src/cli.rs
- src/config.rs
- src/main.rs
- tests/test_flags.rs
- todo.txt
Alternate to 
https://github.com/bootandy/dust/pull/388
> Adding threads flag

- src/config.rs
- src/utils.rs
> Formatting

- src/dir_walker.rs
Before sort_by_inode could result in unstable ordering. This change ensures we will always have a reliable total ordering
> fix: total_ordering of sort_by_inode

- src/config.rs
- src/dir_walker.rs
- src/utils.rs
> fix: perf issues with v1.1.0

- README.md
Fixes #424 
Related to daniejstriata/dust-snap#2
> docs(readme): warn about snap-dust limitations

- README.md
- completions/_dust
- completions/_dust.ps1
- completions/dust.bash
- completions/dust.elv
- completions/dust.fish
- man-page/dust.1
- src/cli.rs
- src/filter.rs
- src/main.rs
- tests/test_flags.rs
--collapse will keep that directory collapsed and will not expand it.
> feat: New --collapse flag

- src/display.rs
The PR fixes the failing style-related CI/CD actions.
> refactor: Fix clippy warnings

- src/main.rs
replace build_global with build
> refactor: ThreadPool use build not build_global

- src/filter.rs
- tests/test_flags.rs
Test to stop bug in previous commit occuring
Also cargo clippy
> tests: add test for d0
